version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: etm-php
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:1.25
    container_name: etm-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: mysql:8.0
    container_name: etm-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: etm
      MYSQL_USER: etm_user
      MYSQL_PASSWORD: etm_pass
    ports:
      - "3307:3306"
    volumes:
      - etm-mysql-data:/var/lib/mysql

volumes:
  etm-mysql-data:
